### ISSUE TITLE
Public Pretrained models

### ISSUE THREAD

**Issue by lehduong** [cpphoo/STARTUP#2]
Hi, thanks for your interesting works and transparency. Although you have provided scripts to reproduce all models, could you also make public the pretrained weights? It would be much appreciated. Thank you.

**Comment by cpphoo** [comment]
Apologies for the extremely long delay. If you still need them, they could be found here: https://drive.google.com/file/d/1UxOkQB4X29UvnyAgESv2Pyye3mecTmQp/view?usp=sharing
